spring.cloud.stream.bindings.school:
  destination: school
spring.cloud.stream.kafka.streams.bindings.school:
  consumer:
    keySerde: com.sample.kafkastreamjoin.serde.SchoolKeySerde
    valueSerde: com.sample.kafkastreamjoin.serde.SchoolSerde
    application-id: stream-join-sample_diff_id_1

spring.cloud.stream.bindings.person:
  destination: person
spring.cloud.stream.kafka.streams.bindings.person:
  consumer:
    keySerde: com.sample.kafkastreamjoin.serde.PersonKeySerde
    valueSerde: com.sample.kafkastreamjoin.serde.PersonSerde
    application-id: stream-join-sample_diff_id_2

spring.cloud.stream.bindings.school_1:
  destination: school
spring.cloud.stream.kafka.streams.bindings.school_1:
  consumer:
    keySerde: com.sample.kafkastreamjoin.serde.SchoolKeySerde
    valueSerde: com.sample.kafkastreamjoin.serde.SchoolSerde
    application-id: stream-join-sample_diff_id_2

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 100